version: 2.1

workflows:
  ci:
    jobs:
      - lint
      - go-test:
          name: test go1.15
          version: "1.15"
      - go-test:
          name: test go1.16
          version: "1.16"
      - go-test:
          name: test go1.16 32bit
          version: "1.16"
          goarch: "386"
          target: ci.test-norace

executors:
  golang:
    parameters:
      version:
        type: string
      goarch:
        type: string
        default: amd64
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:<<parameters.version>>
    environment:
      TEST_RESULTS_DIR: /tmp/test-results
      GOTRACEBACK: "all"
      GO111MODULE: "on"
      GOMAXPROCS: 2
      GOARCH: <<parameters.goarch>>

jobs:
  lint:
    executor:
      name: golang
      version: "1.16"
    steps:
      - checkout
      - run: go mod download

      # check go fmt output because it does not report non-zero when there are fmt changes
      - run:
          name: check go fmt
          command: |
            files=$(go fmt ./...)
            if [ -n "$files" ]; then
              echo "The following file(s) do not conform to go fmt:"
              echo "$files"
              exit 1
            fi
      - run: |
          PACKAGE_NAMES=$(go list ./... | grep -v github.com/hashicorp/raft/fuzzy)
          go vet $PACKAGE_NAMES

  go-test:
    parameters:
      version:
        type: string
      goarch:
        type: string
        default: amd64
      target:
        type: string
        default: ci.integ
    executor:
      name: golang
      version: <<parameters.version>>
      goarch: <<parameters.goarch>>
    steps:
      - run: go env
      - checkout
      - run: mkdir -p $TEST_RESULTS_DIR
      - run: make <<parameters.target>>
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
